### ISSUE TITLE
Decode method : public byte[] Decode(string hexdump)

### ISSUE THREAD

**Issue by lduchosal** [drewnoakes/hex-dump#1]
Hello,

Would you be interested in a method that the inverse encode (Decode) ?

string input =  @"
00000000   01 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
";
var hex = new HexDump();
var bytes = hex.Decode(input);

//  bytes = new byte[] { 01, 00, 00, 00, 00, 00, 00, 00,  00, 00, 00, 00, 00, 00, 00, 00 }

Let me now if interested

**Comment by drewnoakes** [comment]
Interesting idea. What's the use case here?

**Comment by lduchosal** [comment]
I TestUnit network protocol encoding and decoding.
https://github.com/lduchosal/nbtc/blob/master/src/nbtc/Tests/Network/VersionTest.cs

I use pcap dump to build unit tests.

It can go both ways, encode, decode, encode, string must be the same...
https://github.com/lduchosal/nbtc/blob/master/src/nbtc/Tests/HexdumpTest.cs

I would gladly import the Decode method into your project to have a unified nuget.
https://github.com/lduchosal/nbtc/blob/master/src/nbtc/Tests/HexDump.cs

Let me know.

**Comment by lduchosal** [comment]
https://github.com/drewnoakes/hex-dump/pull/3
