### ISSUE TITLE
Static methodes to class methodes

### ISSUE THREAD

**Issue by lduchosal** [drewnoakes/hex-dump#2]
Hello,

I do use DI (dependency injection) and the static method goes against this principle.

Would it be a major issue to have the Encode method non static ?

Let me know

**Comment by drewnoakes** [comment]
I suggest you wrap the static method with your own interface/instance type to use in DI.

I prefer to keep the method as a simple static in this case.

**Comment by lduchosal** [comment]
ok, seems fair. I'll do it this way
